//old client list, only here in case there is ever an issue with the db

const clientList = [
  {
    name: "Misery Signals",
    track: "Ultraviolet",
    credit: "E",
    credits: {
      production: false,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2020",
    spotify: "7eyNB08HF04LwM3eoFTWVI?si=7hwQEKu1TCO2jSxzprw0sA",
    id: "1",
  },
  {
    name: "Spirit Box",
    track: "Self Titled",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2018",
    spotify: "7DEB7wxNm06UGw3eg7kZZf?si=ygLhW62XSm-bTiMujM5Gxw",
    id: "2",
  },
  {
    name: "Spirit Box",
    track: "Singles Collection",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "3AoDOr5fPNjEHIeNKPhzyk?si=vm79jROpSwG-HXLmCH5e6A",
    id: "3",
  },
  {
    name: "Parting Ways",
    track: "Meant Well",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "0BnNqlx3Ojmd8bUBKixl5t?si=fqClDpkkRa2tHYS8qjNz8A",
    id: "4",
  },
  {
    name: "Chief State",
    track: "Nothing More Than This",
    credit: "P/E/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: true,
    },
    writeup: "",
    year: "2018",
    spotify: "0VwkNZgt8JlJCJD0CCrxtr?si=iBzIVLEuSueB8DYgX73vHA",
    id: "5",
  },
  {
    name: "Chief State",
    track: "Tough Love",
    credit: "P/E/M/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: true,
      mastering: true,
    },
    writeup: "",
    year: "2020",
    spotify: "6qlr7cWs4idpqdGbuNFCCp?si=CmO4PepvQ5-Zwqq4eVZ9Dw",
    id: "6",
  },
  {
    name: "Wormwitch",
    track: "Heaven That Dwells Within",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "6xy0sRr85uuiabKilzPFZH?si=cTzJmkHVT5SKaDD0zMOFKA",
    id: "7",
  },
  {
    name: "Of Modern Architecture",
    track: "Matricide",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "0kOpxqlYBQ66KT2cemh48S?si=c9vA0TA5Q7OlB-Q5PN5m8g",
    id: "8",
  },
  {
    name: "Vultures",
    track: "Hunger",
    credit: "P/E/M/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: true,
      mastering: true,
    },
    writeup: "",
    year: "2019",
    spotify: "109xMeM8nxjdK8kCI8gvBV?si=JLKumZsvQZm6zLeRMr285w",
    id: "9",
  },
  {
    name: "Clara Swan",
    track: "Empty Space",
    credit: "P/E/M/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: true,
      mastering: true,
    },
    writeup: "",
    year: "2019",
    spotify: "2UNWsVlyhkG8YLS9NEtqIM?si=hngRWzqhRqSM13xvXqhuEQ",
    id: "10",
  },
  {
    name: "Chief State",
    track: "I’ll Be A Mess Without You",
    credit: "P/E/M/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: true,
      mastering: true,
    },
    writeup: "",
    year: "2019",
    spotify: "4f19llBb0FydWMbeUBLwyF",
    id: "11",
  },
  {
    name: "Seer",
    track: "Children Of The Dying Light",
    credit: "E",
    credits: {
      production: false,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "4kqI5dXVkmQhWzYNI2NXLo?si=KMlZ4z94QW61tJE-yS7P-A",
    id: "12",
  },
  {
    name: "Gleneagle",
    track: "When You Weren't Around",
    credit: "P/E",
    credits: {
      production: true,
      engineering: true,
      mixing: false,
      mastering: false,
    },
    writeup: "",
    year: "2019",
    spotify: "7eKwGjc05XEsUZXqhMxbr4?si=RIIM6pDtQDqjnTgv7vC3gA",
    id: "13",
  },
  {
    name: "Vultures",
    track: "Privileged",
    credit: "P/E//M/MA",
    credits: {
      production: true,
      engineering: true,
      mixing: true,
      mastering: true,
    },
    writeup: "",
    year: "2020",
    spotify: "7eKwGjc05XEsUZXqhMxbr4?si=RIIM6pDtQDqjnTgv7vC3gA",
    id: "14",
  },
];

export default clientList;
